services:
  backend:
    build: ./Backend
    expose:
      - 8000
    volumes:
      - temp_data:/app/.temp
    healthcheck:
      test: ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/8000' || exit 1"]
      interval: 10s
      timeout: 10s

  frontend:
    build: ./Frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=/api
      - BACKEND_URL=http://backend:8000/api
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "--interval=30s --timeout=3s --start-period=5s --retries=3 CMD wget --quiet --tries=1 --spider http://localhost/health || exit 1"]
      interval: 10s
      timeout: 10s

volumes:
  temp_data:
