FROM postgres:16

# Copy initialization script into the image
COPY init_db.sql /docker-entrypoint-initdb.d/

# The postgres image will automatically run any .sql files in /docker-entrypoint-initdb.d/
