import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from app.models.schemas import AnalysisResult
from app.config import settings
import os
from datetime import datetime

class ExportService:
    """
    Generate CSV and PDF reports from analysis results
    """
    
    def generate_csv(self, result: AnalysisResult) -> str:
        """Generate CSV report"""
        data = []
        for phase in result.phases:
            data.append({
                'Phase': phase.phase_name,
                'Status': 'CORRECT' if phase.is_correct else 'ERROR',
                'Score': phase.score,
                'Feedback': phase.feedback,
                'Frame Range': f"{phase.frame_range[0]}-{phase.frame_range[1]}",
                'Errors': '; '.join(phase.error_details) if phase.error_details else 'None'
            })
        
        df = pd.DataFrame(data)
        
        # Add summary row
        summary = pd.DataFrame([{
            'Phase': 'OVERALL',
            'Status': f"{result.total_correct_phases} correct / {result.total_error_phases} errors",
            'Score': result.overall_score,
            'Feedback': f"Duration: {result.duration_seconds:.2f}s",
            'Frame Range': f"Total: {result.total_frames} frames",
            'Errors': ''
        }])
        
        df = pd.concat([df, summary], ignore_index=True)
        
        # Save
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"handstand_analysis_{timestamp}.csv"
        filepath = os.path.join(settings.OUTPUT_DIR, filename)
        df.to_csv(filepath, index=False)
        
        return filepath
    
    def generate_pdf(self, result: AnalysisResult) -> str:
        """Generate PDF report"""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"handstand_analysis_{timestamp}.pdf"
        filepath = os.path.join(settings.OUTPUT_DIR, filename)
        
        c = canvas.Canvas(filepath, pagesize=letter)
        width, height = letter
        
        # Title
        c.setFont("Helvetica-Bold", 24)
        c.drawString(50, height - 50, "Handstand Analysis Report")
        
        # Video info
        c.setFont("Helvetica", 11)
        c.drawString(50, height - 80, f"Video: {result.video_filename}")
        c.drawString(50, height - 95, f"Duration: {result.duration_seconds:.2f} seconds ({result.total_frames} frames)")
        c.drawString(50, height - 110, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        
        # Overall Score Box
        c.setFont("Helvetica-Bold", 18)
        c.setFillColor(colors.HexColor('#2563eb'))
        c.drawString(50, height - 150, f"Overall Score: {result.overall_score}/100")
        
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(colors.HexColor('#16a34a'))
        c.drawString(50, height - 175, f"✓ {result.total_correct_phases} Correct")
        c.setFillColor(colors.HexColor('#dc2626'))
        c.drawString(200, height - 175, f"✗ {result.total_error_phases} Errors")
        
        # Reset color
        c.setFillColor(colors.black)
        
        # Phase breakdown
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 220, "Phase Breakdown:")
        
        y_position = height - 250
        
        for i, phase in enumerate(result.phases, 1):
            # Phase header with status
            c.setFont("Helvetica-Bold", 13)
            status_color = colors.HexColor('#16a34a') if phase.is_correct else colors.HexColor('#dc2626')
            c.setFillColor(status_color)
            status_text = "✓ CORRECT" if phase.is_correct else "✗ ERROR"
            c.drawString(50, y_position, f"{i}. {phase.phase_name}: {status_text}")
            
            # Reset color and font
            c.setFillColor(colors.black)
            c.setFont("Helvetica", 11)
            
            # Score and feedback
            c.drawString(70, y_position - 18, f"Score: {phase.score}/100")
            c.drawString(70, y_position - 33, f"Feedback: {phase.feedback}")
            c.drawString(70, y_position - 48, f"Frames: {phase.frame_range[0]}-{phase.frame_range[1]}")
            
            # Errors if any
            if phase.error_details:
                c.setFillColor(colors.HexColor('#dc2626'))
                c.drawString(70, y_position - 63, f"Issues: {', '.join(phase.error_details)}")
                c.setFillColor(colors.black)
                y_position -= 80
            else:
                y_position -= 70
            
            # Page break if needed
            if y_position < 100:
                c.showPage()
                c.setFont("Helvetica", 11)
                y_position = height - 50
        
        # Footer
        c.setFont("Helvetica-Oblique", 9)
        c.drawString(50, 30, "Generated by Handstand Analyzer API")
        
        c.save()
        return filepath