from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def generate_pdf_report(analysis: dict, output_path: str):
    """Generate PDF analysis report"""
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        topMargin=1.27 * cm,
        bottomMargin=1.27 * cm,
        leftMargin=1.905 * cm,
        rightMargin=1.905 * cm,
    )
    story = []
    styles = getSampleStyleSheet()

    if not analysis:
        story.append(Paragraph("No exercise is detected", styles["h1"]))
        doc.build(story)
        return output_path

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=28,
        textColor=colors.HexColor("#4f46e5"),
        spaceAfter=20,
        alignment=1,
        fontName="Helvetica-Bold",
    )

    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=18,
        textColor=colors.HexColor("#1e40af"),
        spaceAfter=15,
        spaceBefore=15,
        fontName="Helvetica-Bold",
    )

    center_style = ParagraphStyle(
        "CenterStyle",
        parent=styles["Normal"],
        alignment=1,
        fontSize=12,
        leading=14,
    )

    story.append(Spacer(1, 0.508 * cm))
    title = Paragraph("Gym Exercise Analysis Report", title_style)
    story.append(title)

    line_table = Table([[""]], colWidths=[16.51 * cm])
    line_table.setStyle(TableStyle([
        ('LINEBELOW', (0, 0), (-1, -1), 2, colors.HexColor("#4f46e5")),
    ]))
    story.append(line_table)
    story.append(Spacer(1, 0.762 * cm))

    story.append(Paragraph("<b>Overall Score</b>", center_style))
    story.append(Spacer(1, 0.381 * cm))

    story.append(Paragraph(
        f"<font color='#4f46e5'><b>{analysis['overall_score']:.1f}</b></font>"
        f"<font size=28 color='#6b7280'> / {analysis['max_score']}</font>",
        ParagraphStyle(
            "BigScore",
            parent=styles["Normal"],
            alignment=1,
            fontSize=60,
            leading=72,
            spaceBefore=0,
            spaceAfter=0,
        )
    ))
    
    story.append(Spacer(1, 1.016 * cm))
    story.append(Spacer(1, 1.016 * cm))

    story.append(Paragraph("Category Breakdown", heading_style))
    story.append(Spacer(1, 0.381 * cm))

    data = [["Category", "Score", "Max", "%", "Feedback"]]
    for cat in analysis['categories']:
        for pose_data in cat['poses']:
            percentage = (pose_data['score'] / pose_data['max_score']) * 100
            feedback_para = Paragraph(
                pose_data.get('feedback', "Good performance"),
                ParagraphStyle(
                    "feedback",
                    parent=styles["Normal"],
                    fontSize=9,
                    leading=11,
                )
            )
            data.append([
                Paragraph(f"<b>{pose_data['name']}</b>", styles["Normal"]),
                f"{pose_data['score']:.1f}",
                str(pose_data['max_score']),
                f"{percentage:.0f}%",
                feedback_para,
            ])

    table = Table(data, colWidths=[5.08 * cm, 1.778 * cm, 1.778 * cm, 1.778 * cm, 7.366 * cm])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#4f46e5")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, 0), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), "Helvetica-Bold"),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('TOPPADDING', (0, 0), (-1, 0), 10),

        ('ALIGN', (1, 1), (3, -1), 'CENTER'),
        ('ALIGN', (0, 1), (0, -1), 'LEFT'),
        ('ALIGN', (4, 1), (4, -1), 'LEFT'),
        ('FONTNAME', (0, 1), (-1, -1), "Helvetica"),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('TOPPADDING', (0, 1), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),

        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('BOX', (0, 0), (-1, -1), 1.5, colors.HexColor("#4f46e5")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f9fafb")]),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))

    story.append(table)
    story.append(Spacer(1, 1.27 * cm))

    footer_data = [[Paragraph(
        "<para align=center>"
        "<font size=9 color='#6b7280'>"
        "Generated by Gym Analysis AI • Powered by MediaPipe<br/>"
        f"Report Date: {datetime.now().strftime('%B %d, %Y at %H:%M')}"
        "</font>"
        "</para>",
        styles["Normal"]
    )]]

    footer_table = Table(footer_data, colWidths=[16.51 * cm])
    footer_table.setStyle(TableStyle([
        ('LINEABOVE', (0, 0), (-1, 0), 1, colors.HexColor("#e5e7eb")),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
    ]))
    story.append(footer_table)

    doc.build(story)
    return output_path
